name: Android CI

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 12 * * *'
    - cron: '59 23 * * *'

jobs:

  build-debug:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone na-home
      run: cd .. && sudo rm -rf action_build_nahome && git clone https://gitee.com/RobinNotBad/na-home.git action_build_nahome
    - name: ls
      run: ls -l /home/runner/work/action_build_nahome/action_build_nahome
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleDebug
          mv app/build/outputs/nahome/debug/app-debug.apk out/app-debug.apk
    - name: Upload nahome(debug)
      uses: actions/upload-artifact@v3
      with:
          name: app
          path: out/app-debug.*

  build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone na-home
      run: cd .. && sudo rm -rf action_build_nahome && git clone https://gitee.com/RobinNotBad/na-home.git action_build_nahome
    - name: ls
      run: ls -l /home/runner/work/action_build_nahome/action_build_nahome
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleRelease
          mv app/build/outputs/nahome/release/app-release-unsigned.apk out/app-release.apk
    - name: Upload nahome(release)
      uses: actions/upload-artifact@v3
      with:
          name: app
          path: out/app-release.*   
